version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - GIT_NAME=${GIT_NAME}
        - GIT_EMAIL=${GIT_EMAIL}
        - GIT_SSH_PRIVATE_KEY=${GIT_SSH_PRIVATE_KEY}
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
