# Generated by Django 3.2.24 on 2024-02-25 17:46

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20240222_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(null=True, upload_to=apps.core.models.recipe_image_file_path),
        ),
    ]
