#!/bin/bash

set -e
set -u

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
		CREATE DATABASE ${POSTGRES_DB}_test;
	    GRANT ALL PRIVILEGES ON DATABASE ${POSTGRES_DB}_test TO "$POSTGRES_USER";
EOSQL
